kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: developer-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "watch", "update", "patch", "delete", "rollback"]
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list"]
