apiVersion: apps/v1
kind: Deployment
metadata:
  name: shift-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shift
  template:
    metadata:
      labels:
        app: shift
    spec:
      containers:
      - name: shift
        image: php:7.4-apache
        ports:
        - containerPort: 80
      restartPolicy: Always
---
